export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS';
export const UPDATED_APPOINTMENT= 'UPDATED_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';

export const ADD_JOB = 'ADD_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const DELETE_JOB = 'DELETE_JOB';

export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';