export const SCHEDULER_DATE_FORMAT = 'YYYY-MM-DDTHH:mm'

export const APPOINTMENT_STATE_NOT_STARTED = 'APPOINTMENT_STATE_NOT_STARTED'
export const APPOINTMENT_STATE_COMPLETED = 'APPOINTMENT_STATE_COMPLETED'
export const AAPOINTMENT_STATE_DELAYED = 'AAPOINTMENT_STATE_DELAYED'