export const SCHEDULER_DATE_FORMAT = 'YYYY-MM-DDTHH:mm'

export const APPOINTMENT_STATE_TO_DO = 'APPOINTMENT_STATE_TO_DO'
export const APPOINTMENT_STATE_COMPLETED = 'APPOINTMENT_STATE_COMPLETED'

export const SCHEDULE_WORK_ONLY = 'SCHEDULE_WORK_ONLY';
export const SCHEDULE_FREE_TIME = 'SCHEDULE_FREE_TIME';
export const SCHEDULE_FULL = 'SCHEDULE_FULL';

export const JOB_NOT_STARTED = 'JOB_NOT_STARTED';
export const JOB_ON_GOING = 'JOB_ON_GOING';
export const JOB_COMPLETED = 'JOB_COMPLETED';