export const SCHEDULER_DATE_FORMAT = 'YYYY-MM-DDTHH:mm'

export const APPOINTMENT_STATE_NOT_STARTED = 'APPOINTMENT_STATE_NOT_STARTED'
export const APPOINTMENT_STATE_COMPLETED = 'APPOINTMENT_STATE_COMPLETED'
export const APPOINTMENT_STATE_DELAYED = 'APPOINTMENT_STATE_DELAYED'

export const SCHEDULE_WORK_ONLY = 'SCHEDULE_WORK_ONLY';
export const SCHEDULE_FREE_TIME = 'SCHEDULE_FREE_TIME';
export const SCHEDULE_FULL = 'SCHEDULE_FULL';